[build]
  publish = "dist/"
  command = "npm run generate"

[build.processing]
  skip_processing = true

[[plugins]]
  package = "netlify-plugin-csp-generator"

  [plugins.inputs]
    buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'" # Required due to bug in Firefox when loading SVGs with <use> (https://bugzilla.mozilla.org/show_bug.cgi?id=1303364)
    childSrc = "'none'"
    connectSrc = "'none'"
    mediaSrc = "'none'"
    objectSrc = "'none'"
    prefetchSrc = "'none'"
    scriptSrc = "'self'"
    styleSrc = "'self'"
    fontSrc = "'self'"
    imgSrc = "'self'"
    manifestSrc = "'self'"
    baseUri = "'none'"
    formAction = "'none'"
    frameAncestors = "'none'"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  checkExternal = true
